[package]
name = "pipewire-sdl-video-player"
version = "0.1.0"
edition = "2021"

[dependencies]
pipewire-wrapper = { path = "../.." }
sdl2 = { version = "0.35.2", features = ["unsafe_textures"] }
pw_sys = { package = "pipewire-sys", version = "0.6.0" }
