use pipewire_macro_impl::enum_wrapper;

use crate::spa::type_::pod::PodIntRef;

#[allow(non_camel_case_types)]
#[repr(u32)]
pub enum FormatType {
    MEDIA_TYPE(MediaType) = Format::MEDIATYPE.raw,
    MEDIA_SUBTYPE(MediaSubType) = Format::MEDIASUBTYPE.raw,

    AUDIO_FORMAT(AudioFormat) = Format::AUDIO_FORMAT.raw,
    AUDIO_FLAGS(PodIntRef) = Format::AUDIO_FLAGS.raw,
    AUDIO_RATE(PodIntRef) = Format::AUDIO_RATE.raw,
    AUDIO_POSITION() = Format::AUDIO_POSITION.raw,
}

pub enum FormatMediaType {}

enum_wrapper!(
    MediaType,
    spa_sys::spa_media_type,
    UNKNOWN: spa_sys::SPA_MEDIA_TYPE_unknown,
    AUDIO: spa_sys::SPA_MEDIA_TYPE_audio,
    VIDEO: spa_sys::SPA_MEDIA_TYPE_video,
    IMAGE: spa_sys::SPA_MEDIA_TYPE_image,
    BINARY: spa_sys::SPA_MEDIA_TYPE_binary,
    STREAM: spa_sys::SPA_MEDIA_TYPE_stream,
    APPLICATION: spa_sys::SPA_MEDIA_TYPE_application,
);

enum_wrapper!(
    MediaSubType,
    spa_sys::spa_media_subtype,
    UNKNOWN: spa_sys::SPA_MEDIA_SUBTYPE_unknown,
    RAW: spa_sys::SPA_MEDIA_SUBTYPE_raw,
    DSP: spa_sys::SPA_MEDIA_SUBTYPE_dsp,
    IEC958: spa_sys::SPA_MEDIA_SUBTYPE_iec958,
    DSD: spa_sys::SPA_MEDIA_SUBTYPE_dsd,
    AUDIO: spa_sys::SPA_MEDIA_SUBTYPE_START_Audio,
    MP3: spa_sys::SPA_MEDIA_SUBTYPE_mp3,
    AAC: spa_sys::SPA_MEDIA_SUBTYPE_aac,
    VORBIS: spa_sys::SPA_MEDIA_SUBTYPE_vorbis,
    WMA: spa_sys::SPA_MEDIA_SUBTYPE_wma,
    RA: spa_sys::SPA_MEDIA_SUBTYPE_ra,
    SBC: spa_sys::SPA_MEDIA_SUBTYPE_sbc,
    ADPCM: spa_sys::SPA_MEDIA_SUBTYPE_adpcm,
    G723: spa_sys::SPA_MEDIA_SUBTYPE_g723,
    G726: spa_sys::SPA_MEDIA_SUBTYPE_g726,
    G729: spa_sys::SPA_MEDIA_SUBTYPE_g729,
    AMR: spa_sys::SPA_MEDIA_SUBTYPE_amr,
    GSM: spa_sys::SPA_MEDIA_SUBTYPE_gsm,
    VIDEO: spa_sys::SPA_MEDIA_SUBTYPE_START_Video,
    H264: spa_sys::SPA_MEDIA_SUBTYPE_h264,
    MJPG: spa_sys::SPA_MEDIA_SUBTYPE_mjpg,
    DV: spa_sys::SPA_MEDIA_SUBTYPE_dv,
    MPEGTS: spa_sys::SPA_MEDIA_SUBTYPE_mpegts,
    H263: spa_sys::SPA_MEDIA_SUBTYPE_h263,
    MPEG1: spa_sys::SPA_MEDIA_SUBTYPE_mpeg1,
    MPEG2: spa_sys::SPA_MEDIA_SUBTYPE_mpeg2,
    MPEG4: spa_sys::SPA_MEDIA_SUBTYPE_mpeg4,
    XVID: spa_sys::SPA_MEDIA_SUBTYPE_xvid,
    VC1: spa_sys::SPA_MEDIA_SUBTYPE_vc1,
    VP8: spa_sys::SPA_MEDIA_SUBTYPE_vp8,
    VP9: spa_sys::SPA_MEDIA_SUBTYPE_vp9,
    BAYER: spa_sys::SPA_MEDIA_SUBTYPE_bayer,
    IMAGE: spa_sys::SPA_MEDIA_SUBTYPE_START_Image,
    JPEG: spa_sys::SPA_MEDIA_SUBTYPE_jpeg,
    BINARY: spa_sys::SPA_MEDIA_SUBTYPE_START_Binary,
    STREAM: spa_sys::SPA_MEDIA_SUBTYPE_START_Stream,
    MIDI: spa_sys::SPA_MEDIA_SUBTYPE_midi,
    APPLICATION: spa_sys::SPA_MEDIA_SUBTYPE_START_Application,
    CONTROL: spa_sys::SPA_MEDIA_SUBTYPE_control,
);

enum_wrapper!(
    Format,
    spa_sys::spa_format,
    START: spa_sys::SPA_FORMAT_START,
    MEDIATYPE: spa_sys::SPA_FORMAT_mediaType,
    MEDIASUBTYPE: spa_sys::SPA_FORMAT_mediaSubtype,
    START_AUDIO: spa_sys::SPA_FORMAT_START_Audio,
    AUDIO_FORMAT: spa_sys::SPA_FORMAT_AUDIO_format,
    AUDIO_FLAGS: spa_sys::SPA_FORMAT_AUDIO_flags,
    AUDIO_RATE: spa_sys::SPA_FORMAT_AUDIO_rate,
    AUDIO_CHANNELS: spa_sys::SPA_FORMAT_AUDIO_channels,
    AUDIO_POSITION: spa_sys::SPA_FORMAT_AUDIO_position,
    AUDIO_IEC958CODEC: spa_sys::SPA_FORMAT_AUDIO_iec958Codec,
    AUDIO_BITORDER: spa_sys::SPA_FORMAT_AUDIO_bitorder,
    AUDIO_INTERLEAVE: spa_sys::SPA_FORMAT_AUDIO_interleave,
    START_VIDEO: spa_sys::SPA_FORMAT_START_Video,
    VIDEO_FORMAT: spa_sys::SPA_FORMAT_VIDEO_format,
    VIDEO_MODIFIER: spa_sys::SPA_FORMAT_VIDEO_modifier,
    VIDEO_SIZE: spa_sys::SPA_FORMAT_VIDEO_size,
    VIDEO_FRAMERATE: spa_sys::SPA_FORMAT_VIDEO_framerate,
    VIDEO_MAXFRAMERATE: spa_sys::SPA_FORMAT_VIDEO_maxFramerate,
    VIDEO_VIEWS: spa_sys::SPA_FORMAT_VIDEO_views,
    VIDEO_INTERLACEMODE: spa_sys::SPA_FORMAT_VIDEO_interlaceMode,
    VIDEO_PIXELASPECTRATIO: spa_sys::SPA_FORMAT_VIDEO_pixelAspectRatio,
    VIDEO_MULTIVIEWMODE: spa_sys::SPA_FORMAT_VIDEO_multiviewMode,
    VIDEO_MULTIVIEWFLAGS: spa_sys::SPA_FORMAT_VIDEO_multiviewFlags,
    VIDEO_CHROMASITE: spa_sys::SPA_FORMAT_VIDEO_chromaSite,
    VIDEO_COLORRANGE: spa_sys::SPA_FORMAT_VIDEO_colorRange,
    VIDEO_COLORMATRIX: spa_sys::SPA_FORMAT_VIDEO_colorMatrix,
    VIDEO_TRANSFERFUNCTION: spa_sys::SPA_FORMAT_VIDEO_transferFunction,
    VIDEO_COLORPRIMARIES: spa_sys::SPA_FORMAT_VIDEO_colorPrimaries,
    VIDEO_PROFILE: spa_sys::SPA_FORMAT_VIDEO_profile,
    VIDEO_LEVEL: spa_sys::SPA_FORMAT_VIDEO_level,
    VIDEO_H264_STREAMFORMAT: spa_sys::SPA_FORMAT_VIDEO_H264_streamFormat,
    VIDEO_H264_ALIGNMENT: spa_sys::SPA_FORMAT_VIDEO_H264_alignment,
    START_IMAGE: spa_sys::SPA_FORMAT_START_Image,
    START_BINARY: spa_sys::SPA_FORMAT_START_Binary,
    START_STREAM: spa_sys::SPA_FORMAT_START_Stream,
    START_APPLICATION: spa_sys::SPA_FORMAT_START_Application,
);

enum_wrapper!(
    AudioFormat,
    spa_sys::spa_format,
    UNKNOWN: spa_sys::SPA_AUDIO_FORMAT_UNKNOWN,
    ENCODED: spa_sys::SPA_AUDIO_FORMAT_ENCODED,
    START_INTERLEAVED: spa_sys::SPA_AUDIO_FORMAT_START_Interleaved,
    S8: spa_sys::SPA_AUDIO_FORMAT_S8,
    U8: spa_sys::SPA_AUDIO_FORMAT_U8,
    S16_LE: spa_sys::SPA_AUDIO_FORMAT_S16_LE,
    S16_BE: spa_sys::SPA_AUDIO_FORMAT_S16_BE,
    U16_LE: spa_sys::SPA_AUDIO_FORMAT_U16_LE,
    U16_BE: spa_sys::SPA_AUDIO_FORMAT_U16_BE,
    S24_32_LE: spa_sys::SPA_AUDIO_FORMAT_S24_32_LE,
    S24_32_BE: spa_sys::SPA_AUDIO_FORMAT_S24_32_BE,
    U24_32_LE: spa_sys::SPA_AUDIO_FORMAT_U24_32_LE,
    U24_32_BE: spa_sys::SPA_AUDIO_FORMAT_U24_32_BE,
    S32_LE: spa_sys::SPA_AUDIO_FORMAT_S32_LE,
    S32_BE: spa_sys::SPA_AUDIO_FORMAT_S32_BE,
    U32_LE: spa_sys::SPA_AUDIO_FORMAT_U32_LE,
    U32_BE: spa_sys::SPA_AUDIO_FORMAT_U32_BE,
    S24_LE: spa_sys::SPA_AUDIO_FORMAT_S24_LE,
    S24_BE: spa_sys::SPA_AUDIO_FORMAT_S24_BE,
    U24_LE: spa_sys::SPA_AUDIO_FORMAT_U24_LE,
    U24_BE: spa_sys::SPA_AUDIO_FORMAT_U24_BE,
    S20_LE: spa_sys::SPA_AUDIO_FORMAT_S20_LE,
    S20_BE: spa_sys::SPA_AUDIO_FORMAT_S20_BE,
    U20_LE: spa_sys::SPA_AUDIO_FORMAT_U20_LE,
    U20_BE: spa_sys::SPA_AUDIO_FORMAT_U20_BE,
    S18_LE: spa_sys::SPA_AUDIO_FORMAT_S18_LE,
    S18_BE: spa_sys::SPA_AUDIO_FORMAT_S18_BE,
    U18_LE: spa_sys::SPA_AUDIO_FORMAT_U18_LE,
    U18_BE: spa_sys::SPA_AUDIO_FORMAT_U18_BE,
    F32_LE: spa_sys::SPA_AUDIO_FORMAT_F32_LE,
    F32_BE: spa_sys::SPA_AUDIO_FORMAT_F32_BE,
    F64_LE: spa_sys::SPA_AUDIO_FORMAT_F64_LE,
    F64_BE: spa_sys::SPA_AUDIO_FORMAT_F64_BE,
    ULAW: spa_sys::SPA_AUDIO_FORMAT_ULAW,
    ALAW: spa_sys::SPA_AUDIO_FORMAT_ALAW,
    START_PLANAR: spa_sys::SPA_AUDIO_FORMAT_START_Planar,
    U8P: spa_sys::SPA_AUDIO_FORMAT_U8P,
    S16P: spa_sys::SPA_AUDIO_FORMAT_S16P,
    S24_32P: spa_sys::SPA_AUDIO_FORMAT_S24_32P,
    S32P: spa_sys::SPA_AUDIO_FORMAT_S32P,
    S24P: spa_sys::SPA_AUDIO_FORMAT_S24P,
    F32P: spa_sys::SPA_AUDIO_FORMAT_F32P,
    F64P: spa_sys::SPA_AUDIO_FORMAT_F64P,
    S8P: spa_sys::SPA_AUDIO_FORMAT_S8P,
    START_OTHER: spa_sys::SPA_AUDIO_FORMAT_START_Other,
    DSP_S32: spa_sys::SPA_AUDIO_FORMAT_DSP_S32,
    DSP_F32: spa_sys::SPA_AUDIO_FORMAT_DSP_F32,
    DSP_F64: spa_sys::SPA_AUDIO_FORMAT_DSP_F64,
    S16: spa_sys::SPA_AUDIO_FORMAT_S16,
    U16: spa_sys::SPA_AUDIO_FORMAT_U16,
    S24_32: spa_sys::SPA_AUDIO_FORMAT_S24_32,
    U24_32: spa_sys::SPA_AUDIO_FORMAT_U24_32,
    S32: spa_sys::SPA_AUDIO_FORMAT_S32,
    U32: spa_sys::SPA_AUDIO_FORMAT_U32,
    S24: spa_sys::SPA_AUDIO_FORMAT_S24,
    U24: spa_sys::SPA_AUDIO_FORMAT_U24,
    S20: spa_sys::SPA_AUDIO_FORMAT_S20,
    U20: spa_sys::SPA_AUDIO_FORMAT_U20,
    S18: spa_sys::SPA_AUDIO_FORMAT_S18,
    U18: spa_sys::SPA_AUDIO_FORMAT_U18,
    F32: spa_sys::SPA_AUDIO_FORMAT_F32,
    F64: spa_sys::SPA_AUDIO_FORMAT_F64,
    S16_OE: spa_sys::SPA_AUDIO_FORMAT_S16_OE,
    U16_OE: spa_sys::SPA_AUDIO_FORMAT_U16_OE,
    S24_32_OE: spa_sys::SPA_AUDIO_FORMAT_S24_32_OE,
    U24_32_OE: spa_sys::SPA_AUDIO_FORMAT_U24_32_OE,
    S32_OE: spa_sys::SPA_AUDIO_FORMAT_S32_OE,
    U32_OE: spa_sys::SPA_AUDIO_FORMAT_U32_OE,
    S24_OE: spa_sys::SPA_AUDIO_FORMAT_S24_OE,
    U24_OE: spa_sys::SPA_AUDIO_FORMAT_U24_OE,
    S20_OE: spa_sys::SPA_AUDIO_FORMAT_S20_OE,
    U20_OE: spa_sys::SPA_AUDIO_FORMAT_U20_OE,
    S18_OE: spa_sys::SPA_AUDIO_FORMAT_S18_OE,
    U18_OE: spa_sys::SPA_AUDIO_FORMAT_U18_OE,
    F32_OE: spa_sys::SPA_AUDIO_FORMAT_F32_OE,
    F64_OE: spa_sys::SPA_AUDIO_FORMAT_F64_OE,
);

enum_wrapper!(
    AudioChannel,
    spa_sys::spa_audio_channel,
    UNKNOWN: spa_sys::SPA_AUDIO_CHANNEL_UNKNOWN,
    NA: spa_sys::SPA_AUDIO_CHANNEL_NA,
    MONO: spa_sys::SPA_AUDIO_CHANNEL_MONO,
    FL: spa_sys::SPA_AUDIO_CHANNEL_FL,
    FR: spa_sys::SPA_AUDIO_CHANNEL_FR,
    FC: spa_sys::SPA_AUDIO_CHANNEL_FC,
    LFE: spa_sys::SPA_AUDIO_CHANNEL_LFE,
    SL: spa_sys::SPA_AUDIO_CHANNEL_SL,
    SR: spa_sys::SPA_AUDIO_CHANNEL_SR,
    FLC: spa_sys::SPA_AUDIO_CHANNEL_FLC,
    FRC: spa_sys::SPA_AUDIO_CHANNEL_FRC,
    RC: spa_sys::SPA_AUDIO_CHANNEL_RC,
    RL: spa_sys::SPA_AUDIO_CHANNEL_RL,
    RR: spa_sys::SPA_AUDIO_CHANNEL_RR,
    TC: spa_sys::SPA_AUDIO_CHANNEL_TC,
    TFL: spa_sys::SPA_AUDIO_CHANNEL_TFL,
    TFC: spa_sys::SPA_AUDIO_CHANNEL_TFC,
    TFR: spa_sys::SPA_AUDIO_CHANNEL_TFR,
    TRL: spa_sys::SPA_AUDIO_CHANNEL_TRL,
    TRC: spa_sys::SPA_AUDIO_CHANNEL_TRC,
    TRR: spa_sys::SPA_AUDIO_CHANNEL_TRR,
    RLC: spa_sys::SPA_AUDIO_CHANNEL_RLC,
    RRC: spa_sys::SPA_AUDIO_CHANNEL_RRC,
    FLW: spa_sys::SPA_AUDIO_CHANNEL_FLW,
    FRW: spa_sys::SPA_AUDIO_CHANNEL_FRW,
    LFE2: spa_sys::SPA_AUDIO_CHANNEL_LFE2,
    FLH: spa_sys::SPA_AUDIO_CHANNEL_FLH,
    FCH: spa_sys::SPA_AUDIO_CHANNEL_FCH,
    FRH: spa_sys::SPA_AUDIO_CHANNEL_FRH,
    TFLC: spa_sys::SPA_AUDIO_CHANNEL_TFLC,
    TFRC: spa_sys::SPA_AUDIO_CHANNEL_TFRC,
    TSL: spa_sys::SPA_AUDIO_CHANNEL_TSL,
    TSR: spa_sys::SPA_AUDIO_CHANNEL_TSR,
    LLFE: spa_sys::SPA_AUDIO_CHANNEL_LLFE,
    RLFE: spa_sys::SPA_AUDIO_CHANNEL_RLFE,
    BC: spa_sys::SPA_AUDIO_CHANNEL_BC,
    BLC: spa_sys::SPA_AUDIO_CHANNEL_BLC,
    BRC: spa_sys::SPA_AUDIO_CHANNEL_BRC,
    START_AUX: spa_sys::SPA_AUDIO_CHANNEL_START_Aux,
    AUX0: spa_sys::SPA_AUDIO_CHANNEL_AUX0,
    AUX1: spa_sys::SPA_AUDIO_CHANNEL_AUX1,
    AUX2: spa_sys::SPA_AUDIO_CHANNEL_AUX2,
    AUX3: spa_sys::SPA_AUDIO_CHANNEL_AUX3,
    AUX4: spa_sys::SPA_AUDIO_CHANNEL_AUX4,
    AUX5: spa_sys::SPA_AUDIO_CHANNEL_AUX5,
    AUX6: spa_sys::SPA_AUDIO_CHANNEL_AUX6,
    AUX7: spa_sys::SPA_AUDIO_CHANNEL_AUX7,
    AUX8: spa_sys::SPA_AUDIO_CHANNEL_AUX8,
    AUX9: spa_sys::SPA_AUDIO_CHANNEL_AUX9,
    AUX10: spa_sys::SPA_AUDIO_CHANNEL_AUX10,
    AUX11: spa_sys::SPA_AUDIO_CHANNEL_AUX11,
    AUX12: spa_sys::SPA_AUDIO_CHANNEL_AUX12,
    AUX13: spa_sys::SPA_AUDIO_CHANNEL_AUX13,
    AUX14: spa_sys::SPA_AUDIO_CHANNEL_AUX14,
    AUX15: spa_sys::SPA_AUDIO_CHANNEL_AUX15,
    AUX16: spa_sys::SPA_AUDIO_CHANNEL_AUX16,
    AUX17: spa_sys::SPA_AUDIO_CHANNEL_AUX17,
    AUX18: spa_sys::SPA_AUDIO_CHANNEL_AUX18,
    AUX19: spa_sys::SPA_AUDIO_CHANNEL_AUX19,
    AUX20: spa_sys::SPA_AUDIO_CHANNEL_AUX20,
    AUX21: spa_sys::SPA_AUDIO_CHANNEL_AUX21,
    AUX22: spa_sys::SPA_AUDIO_CHANNEL_AUX22,
    AUX23: spa_sys::SPA_AUDIO_CHANNEL_AUX23,
    AUX24: spa_sys::SPA_AUDIO_CHANNEL_AUX24,
    AUX25: spa_sys::SPA_AUDIO_CHANNEL_AUX25,
    AUX26: spa_sys::SPA_AUDIO_CHANNEL_AUX26,
    AUX27: spa_sys::SPA_AUDIO_CHANNEL_AUX27,
    AUX28: spa_sys::SPA_AUDIO_CHANNEL_AUX28,
    AUX29: spa_sys::SPA_AUDIO_CHANNEL_AUX29,
    AUX30: spa_sys::SPA_AUDIO_CHANNEL_AUX30,
    AUX31: spa_sys::SPA_AUDIO_CHANNEL_AUX31,
    AUX32: spa_sys::SPA_AUDIO_CHANNEL_AUX32,
    AUX33: spa_sys::SPA_AUDIO_CHANNEL_AUX33,
    AUX34: spa_sys::SPA_AUDIO_CHANNEL_AUX34,
    AUX35: spa_sys::SPA_AUDIO_CHANNEL_AUX35,
    AUX36: spa_sys::SPA_AUDIO_CHANNEL_AUX36,
    AUX37: spa_sys::SPA_AUDIO_CHANNEL_AUX37,
    AUX38: spa_sys::SPA_AUDIO_CHANNEL_AUX38,
    AUX39: spa_sys::SPA_AUDIO_CHANNEL_AUX39,
    AUX40: spa_sys::SPA_AUDIO_CHANNEL_AUX40,
    AUX41: spa_sys::SPA_AUDIO_CHANNEL_AUX41,
    AUX42: spa_sys::SPA_AUDIO_CHANNEL_AUX42,
    AUX43: spa_sys::SPA_AUDIO_CHANNEL_AUX43,
    AUX44: spa_sys::SPA_AUDIO_CHANNEL_AUX44,
    AUX45: spa_sys::SPA_AUDIO_CHANNEL_AUX45,
    AUX46: spa_sys::SPA_AUDIO_CHANNEL_AUX46,
    AUX47: spa_sys::SPA_AUDIO_CHANNEL_AUX47,
    AUX48: spa_sys::SPA_AUDIO_CHANNEL_AUX48,
    AUX49: spa_sys::SPA_AUDIO_CHANNEL_AUX49,
    AUX50: spa_sys::SPA_AUDIO_CHANNEL_AUX50,
    AUX51: spa_sys::SPA_AUDIO_CHANNEL_AUX51,
    AUX52: spa_sys::SPA_AUDIO_CHANNEL_AUX52,
    AUX53: spa_sys::SPA_AUDIO_CHANNEL_AUX53,
    AUX54: spa_sys::SPA_AUDIO_CHANNEL_AUX54,
    AUX55: spa_sys::SPA_AUDIO_CHANNEL_AUX55,
    AUX56: spa_sys::SPA_AUDIO_CHANNEL_AUX56,
    AUX57: spa_sys::SPA_AUDIO_CHANNEL_AUX57,
    AUX58: spa_sys::SPA_AUDIO_CHANNEL_AUX58,
    AUX59: spa_sys::SPA_AUDIO_CHANNEL_AUX59,
    AUX60: spa_sys::SPA_AUDIO_CHANNEL_AUX60,
    AUX61: spa_sys::SPA_AUDIO_CHANNEL_AUX61,
    AUX62: spa_sys::SPA_AUDIO_CHANNEL_AUX62,
    AUX63: spa_sys::SPA_AUDIO_CHANNEL_AUX63,
    LAST_AUX: spa_sys::SPA_AUDIO_CHANNEL_LAST_Aux,
    START_CUSTOM: spa_sys::SPA_AUDIO_CHANNEL_START_Custom,
);
