name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install PipeWire
        run: sudo apt-get install -y pipewire libpipewire-0.3-dev libspa-0.2-dev
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/llvm-16
          key: llvm-3.5
      # LLVM and Clang
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 16
          directory: ${{ runner.temp }}/llvm-16
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm-16/lib
          RUST_TEST_THREADS: 1
        with:
          command: test
          args: --verbose -- --nocapture
