name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install LLVM
    - uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"
        
    - name: Install rust toolchain
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    # See:
    # https://github.com/rust-lang/rust-bindgen/issues/1797
    # https://github.com/KyleMayes/clang-sys/issues/121
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      
    - name: Checkout  
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
